export const application = {
    READY: 'APPLICATION_READY',
    LOADING: 'APPLICATION_LOADING',
    GET_CLIENT_ID: 'APPLICATION_GET_CLIENT_ID',
    SET_CLIENT_ID: 'APPLICATION_SET_CLIENT_ID',
    STORE_CLIENT_ID: 'APPLICATION_STORE_CLIENT_ID',
    SET_PAGE: 'APPLICATION_PAGE',
    HEIGHT: 'APPLICATION_HEIGHT',
    WIDTH: 'APPLICATION_WIDTH',
    SET_DIMENSIONS: 'APPLICATION_SET_DIMENSIONS',
};

export const movies = {
    LOADING: 'MOVIES_LOADING',
    CHANGE_QUERY: 'MOVIES_CHANGE_QUERY',
    SET_QUERY: 'MOVIES_SET_QUERY',
    CLEAR_QUERY: 'MOVIES_CLEAR_QUERY',
    ALLOW_SEARCH: 'MOVIES_ALLOW_SEARCH',
    SEARCH: 'MOVIES_SEARCH',
    SET_PAGER: 'MOVIES_SET_PAGER',
};

export const favorites = {
    PAGE_FAVS: 'FAVORITES_PAGE_FAVS',
    CLEAR_PAGE_FAVS: 'FAVORITES_CLEAR_PAGE_FAVS',
    FAV_REQUEST: 'FAVORITES_FAV_REQUEST',
    RESET_FAV_REQUEST: 'FAVORITES_RESET_FAV_REQUEST',
    REQUEST_PAGE_FAVORITES: 'FAVORITES_REQUEST_PAGE_FAVORITES',
    DELETE_DIALOG: 'FAVORITES_DELETE_DIALOG',
    SET_DELETE_OBJECT: 'FAVORITES_SET_DELETE_OBJECT',
    REMOVING: 'FAVORITES_REMOVING',
    DELETE: 'FAVORITES_DELETE',
    REQUEST_OBJECT: 'FAVORITES_REQUEST_OBJECT',
    REQUEST_ITEMS: 'FAVORITES_REQUEST_ITEMS',
    REQUEST_DELETE: 'FAVORITES_REQUEST_DELETE',
    SET_PAGER: 'FAVORITES_SET_PAGER',
    SET_ITEMS: 'FAVORITES_SET_ITEMS',
    LOADING: 'FAVORITES_LOADING',
    CHANGE_QUERY: 'FAVORITES_CHANGE_QUERY',
    SET_QUERY: 'FAVORITES_SET_QUERY',
    CLEAR_QUERY: 'FAVORITES_CLEAR_QUERY',
    ALLOW_SEARCH: 'FAVORITES_ALLOW_SEARCH',
    SEARCH: 'FAVORITES_SEARCH',
};

export const movie = {
    REQUEST: 'MOVIE_REQUEST',
    SET_MOVIE: 'MOVIE_SET_MOVIE',
    SET_ID: 'MOVIE_SET_ID',
    CLEAR: 'MOVIE_CLEAR',
};
